# How the draft is named/tagged while you iterate
name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"

# Group PRs by label (order matters)
categories:
  - title: "🚀 Features"
    labels: ["feature", "enhancement"]
  - title: "📝 Request"
    labels: ["request", "feature-request"]
  - title: "❗ Issue"
    labels: ["issue", "incident"]
  - title: "🐛 Bug Fixes"
    labels: ["bug", "fix"]
  - title: "🛠 Maintenance"
    labels: ["chore", "refactor", "ci", "infrastructure"]
  - title: "📚 Documentation"
    labels: ["docs"]
  - title: "⬆️ Dependencies"
    labels: ["dependencies"]
  - title: "Other Changes"
    labels: ["*"] # catch-all for anything unlabeled

exclude-labels:
  - "skip-changelog"

# How each PR line looks
change-template: "- $TITLE (#$NUMBER)"

# Drive SemVer bump from labels (adjust if you like)
version-resolver:
  major:
    labels: ["major", "breaking-change"]
  minor:
    labels: ["minor", "feature", "enhancement", "request", "feature-request"]
  patch:
    labels:
      [
        "patch",
        "bug",
        "fix",
        "issue",
        "incident",
        "chore",
        "ci",
        "docs",
        "dependencies",
      ]
  default: patch

# Auto-apply labels to PRs (optional, helps the grouping above)
autolabeler:
  - label: "feature"
    branch:
      - "/^feature\\/.+/"
    title:
      - "/\\bfeat(ure)?\\b/i"
  - label: "request"
    branch:
      - "/^request\\/.+/"
    title:
      - "/\\b(feature\\s*request|request)\\b/i"
  - label: "issue"
    branch:
      - "/^issue\\/.+/"
    title:
      - "/\\bissue\\b/i"
  - label: "bug"
    branch:
      - "/^fix\\/.+/"
    title:
      - "/\\bfix(e|es|ed)?\\b/i"
  - label: "docs"
    files:
      - "*.md"
      - "docs/**"
  - label: "chore"
    branch:
      - "/^chore\\/.+/"
  - label: "dependencies"
    title:
      - "/\\b(dependabot|bump|upgrade)\\b/i"

# Your release body template
template: |
  ## Functional tests (Check for Mayor and Minor releases)

  - [ ] Log out and log in successful
  - [ ] Visit and show table
  - [ ] Download table as Excel
  - [ ] Download table as CSV
  - [ ] Download table as pdf
  - [ ] Download table via api
  - [ ] Import countries
  - [ ] Check country report
  - [ ] Download country report as pdf

  ## SonarQube Result (Check for Mayor and Minor releases)

  *Paste screenshot of latest SonarQube Result*

  ## Changelog
  $CHANGES
